apiVersion: v1
kind: ReplicationController
metadata:
  name: bot_demo
  namespace: com-att-cmlp
spec:
  replicas: 5
  selector:
    app: bot_demo
  template:
    metadata:
      labels:
        app: bot_demo
    spec:
      serviceAccount: jb307a
      containers:
      - name: bot_demo
        image: zlp11313.vci.att.com:5100/bot_demo:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080